### ISSUE TITLE
Find alternative datasets to imagenet

### ISSUE THREAD

**Issue by Thunfischpirat** [HLCV-23/Inpainting-Detection#7]
Many images on the image net aren't suitable for malicious forgeries; the partially inpainted dataset we generated from them contains mainly very strange-looking images. Are there better datasets that we can use to create partially inpainted images that aren't perceived as unrealistic at first glance?

**Comment by nicola-mueller** [comment]
This dataset looks promising: https://huggingface.co/datasets/scene_parse_150
It consists of so-called scenes, so I think its less likely to have weird objects.

**Comment by Thunfischpirat** [comment]
https://huggingface.co/datasets/biglam/dating-historical-color-images Suffers from distorted inpainted faces when applying our data generation pipeline to it

**Comment by Thunfischpirat** [comment]
Using only the first prompt generated by `gpt2_pipe` yields realistic-looking inpainted images from the `scenes_parse_150` dataset.

**Comment by Thunfischpirat** [comment]
Experimenting on `imagenet-1k` with the new pipeline also improves image quality there. Is it possible to choose the mask that contains one of the key objects of the image, i.e., the dog in front of a house?

**Comment by Thunfischpirat** [comment]
Closing issue since we found two decent alternative datasets.
